### ISSUE TITLE
MockBukkit Statics and Test Threading

### ISSUE THREAD

**Issue by Narimm** [seeseemelk/MockBukkit#16] opened 2019-02-11 02:28 UTC
I am not sure that this is really a mockbukkit error.  I have a  plugin I have been testing - 
I used the code you suggested to load the plugin - I was initially running MockBukkit.unload() in the teardown but I was getting NPE's when I ran the tests via maven surefire vs locally individually in the IDE
Individually they all pass fine but when you starting running multiple tests in a class - I assume the surefire plugin forks them to threads that call on the static class's which unloading can set as null. hence the my plugin variable ends up as null even though the instance itself is not static. 
The NPE's actually change with each run and sometimes it will run successfully...generally on slower machines...butfast multicore machines always error.

**Comment by seeseemelk** [comment] 2019-02-11 15:50
Hmm, if the surefire plugin is forking them out to different threads you might also run into several other problems. Some methods will actually test if they were called from the same thread that called MockBukkit.mock(), to make sure that your plugin is not accidentally calling them from a different thread.
Can you send me some of those stack traces so that I can try and see if I can reproduce the issue?

**Comment by seeseemelk** [comment] 2019-04-06 14:05
Is this still an issue? If it is you, can you send me project files that you are trying to test?
Otherwise I'll close this issue since I'm running the tests through Gradle and Eclipse, and I'm not running in the issue there.

**Closed** 2019-04-18 10:57 UTC
