### ISSUE TITLE
Add support for World#spawnEntity

### ISSUE THREAD

**Issue by tatanpoker09** [seeseemelk/MockBukkit#25] opened 2019-10-12 18:08 UTC

**Comment by tatanpoker09** [comment] 2019-10-16 16:39
Thanks! If given indications though, I can try to implement it myself and send a pull request

**Comment by seeseemelk** [comment] 2019-10-17 07:30
If you could implement this, that would be awesome because I don't think I'll have enough time soon. If you add this, could you also add some unit tests for this method? Having a unit testing framework with bugs/regressions in it is quite annoying.

**Comment by tatanpoker09** [comment] 2019-10-23 03:11
Yeah sure, I always try to add unit tests (as long as I know how to implement it. Do you know where I can get some info on how to implement? Maybe similar to how players are added?

**Comment by tatanpoker09** [comment] 2019-10-23 06:24
Update: I sent a pull request #26 for this.

**Comment by seeseemelk** [comment] 2019-10-27 09:18
The pull request is merged and an update was pushed to maven central

**Closed by seeseemelk** 2019-10-27 09:18 UTC
